apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-app
  template:
    metadata:
      labels:
        app: budget-app
    spec:
      containers:
        - name: budget-app-container
          image: <your_dockerhub_username>/<image_name>:latest
          env:
            - name: DATABASE_URL
              value: "postgres://<your_database_username>:<your_database_password>@postgres:5432/<your_database_name>"
            - name: HOSTS
              value: "budget-app.local"
          ports:
            - containerPort: 3000
