# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_development # Updated to match your DB name
  username: blog-app # Your DB username
  password: prince@123 # Your DB password
  host: postgres # Host should match the Kubernetes service name
  port: 5432 # Default PostgreSQL port

test:
  <<: *default
  database: blog_app_test # Updated to match your DB name

production:
  <<: *default
  database: blog_app_production # Updated to match your DB name
  username: blog-app # Your DB username
  password: <%= ENV["BUDGET_DATABASE_PASSWORD"] %> # Use environment variable for security
